<?php
$error = $_SESSION['error'] ?? null;
unset($_SESSION['error']);
?>

<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>Přihlášení</title>
    <link rel="stylesheet" href="/public/css/forms.css" />
    <script src="/public/js/hider.js"></script>
</head>
<body>

<?php if ($error): ?>
    <div class="error-message"><?= htmlspecialchars($error) ?></div>
<?php endif; ?>

    <form action="/auth/login" method="POST">
        <h2>Přihlášení</h2>
        <label for="email">Email</label>
        <input type="email" name="email" id="email" required />

        <label for="password">Heslo</label>
        <input type="password" name="password" id="password" required />

        <button type="submit">Přihlásit se</button>
         <p style="text-align:center; margin-top:1rem;">
        Ještě nemáte účet? <a href="/auth/register">Zaregistrujte se zde</a>.
        </p>
    </form>
</body>
</html>
