<?php
$error = $_SESSION['error'] ?? null;
unset($_SESSION['error']);

  $addCss('/public/css/forms.css');
?>

<h2>Registrace nového uživatele</h2>

<?php if ($error): ?>
    <div class="error-message"><?= htmlspecialchars($error) ?></div>
<?php endif; ?>

<form method="post" action="/auth/register" id="RegisterForm">
    <label for="email">Email:</label>
    <input type="email" id="email" name="email" required />

    <label for="password">Heslo:</label>
    <input type="password" id="password" name="password" required />

    <label for="password_confirm">Potvrzení hesla:</label>
    <input type="password" id="password_confirm" name="password_confirm" required />

    <button type="submit">Registrovat</button>
    <p style="text-align:center; margin-top:1rem;">
        Mmáte účet? <a href="/auth/login">Přihlaste se zde</a>.
    </p>
</form>
