<?php
  $addCss('/public/css/todo.css');
  $addJs('/public/js/todo.js');
?>

<h1>Moje Todo Listy</h1>

<?php if (empty($lists)): ?>
    <p>Nemáte žádné todo listy.</p>
<?php else: ?>
    <ul id="todoLists">
        <?php foreach ($lists as $list): ?>
            <li>
                <a href="/todo/<?= htmlspecialchars($list['hash']) ?>">
                    <?= htmlspecialchars($list['title']) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
